Exit with test status

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -9,19 +9,22 @@
 # The default target in this directory is the test:: target
 test:: lib
 	@ echo "Running the test cases..."
-	@ for t in $$(cat auto-tests.txt);\
-		do\
-			printf "\033[37m%-20s" "$$t";\
-			make clean -s -C $$t > /dev/null 2>&1;\
-			make -s -C $$t > /dev/null 2>&1;\
-			make test -s -C $$t DEBUGFLAGS= > /dev/null 2>&1;\
-			if [ $$? -eq 0 ]; then\
-				printf "\033[34m[PASS]\033[0m\n";\
-			else\
-				printf "\033[31m[FAIL]\033[0m\n";\
-			fi;\
-			make clean -s -C $$t > /dev/null 2>&1;\
-		done
+	@ RET=0;\
+	  for t in $$(cat auto-tests.txt);\
+	  do\
+	      printf "\033[37m%-20s" "$$t";\
+	  	  make clean -s -C $$t > /dev/null 2>&1;\
+		  make -s -C $$t > /dev/null 2>&1;\
+		  make test -s -C $$t DEBUGFLAGS= > /dev/null 2>&1;\
+		  if [ $$? -eq 0 ]; then\
+		  	  printf "\033[34m[PASS]\033[0m\n";\
+		  else\
+		      printf "\033[31m[FAIL]\033[0m\n";\
+		      RET=1;\
+		  fi;\
+		  make clean -s -C $$t > /dev/null 2>&1;\
+	  done;\
+	  exit $$RET
 	
 lib:
 	@ echo -n "Building the Giri..."
